project_name: 项目名称
env: 测试环境
tester_name:

# 测试域名
host: http://dev-bms.k7.cn
# 登录用户信息
admin_name: jie
password: e10adc3949ba59abbe56e057f20f883e

 #jenkins相关配置
jenkins:
  # 本地服务
  url: http://yellow-jenkins.kaiqitech.com/
  # 如果有映射网址，可以填在这里
  mapping_url:
  # jenkins账号
  user: jie.jiang
  # jenkins密码
  pwd: jiang123456
  # 要推送的项目名
  project:

# 钉钉消息通知相关配置
ding_talk:
  webhook:

# 数据库相关配置
mysql_db:
  host:
  user:
  password:
  port: 3306
  # true为打开数据库配置,false为关闭
  switch: false

# 邮箱相关配置
email:
  # 邮箱服务类型
  smtp_server:
  # 发送人邮箱
  sender_email:
  # 发送人密码
  password:
  # 接收人邮箱
  receiver_email: